// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScooterService.Data;

#nullable disable

namespace ScooterService.Migrations
{
    [DbContext(typeof(ScooterDbContext))]
    partial class ScooterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScooterService.Entities.ScooterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("SessionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Scooters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6052fd98-d98b-4a2f-9bc8-b90b1e134603"),
                            Model = "UrbanGlide",
                            SessionIds = new List<Guid>(),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("a1c96566-82d5-41ee-a407-db13b6b03dc2"),
                            Model = "SpeedMaster",
                            SessionIds = new List<Guid>(),
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("c9581c77-8f22-4388-ba55-12a087a3ec09"),
                            Model = "TurboScoot",
                            SessionIds = new List<Guid>(),
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("be003688-c1ca-4eb0-a22e-542f445df9c2"),
                            Model = "UrbanGlide",
                            SessionIds = new List<Guid>(),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("94db0ba1-6414-427d-9595-14a1d99a966a"),
                            Model = "TurboScoot",
                            SessionIds = new List<Guid>(),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("1c9d8f60-4bdb-4255-837d-b97e38c0899f"),
                            Model = "XR-1000",
                            SessionIds = new List<Guid>(),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("421546c9-25bd-4806-a0cc-27f723e52a17"),
                            Model = "SpeedMaster",
                            SessionIds = new List<Guid>(),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("3bd6bdf5-98cc-4853-ba91-3bcf09023603"),
                            Model = "XR-1000",
                            SessionIds = new List<Guid>(),
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("4edb2562-cde9-43ee-a527-4cf3802c26d0"),
                            Model = "UrbanGlide",
                            SessionIds = new List<Guid>(),
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("145e70f3-8a2d-4abe-a762-0aa84724e82d"),
                            Model = "UrbanGlide",
                            SessionIds = new List<Guid>(),
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
